
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: 'true, ddaddasd, dasdasd'
};

export default function Home() {
  
  return (
     <h1>HELLO_WORLD</h1>
  );
}
